apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default

spec:
  interval: 1h0m0s
  releaseName: homepage

  chart:
    spec:
      chart: homepage
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
      interval: 2h0m0s

  valuesFrom:
    - kind: ConfigMap
      name: homepage-values
      valuesKey: values.yaml
