apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omnitools
spec:
  values:
    app:
      image:
        tag: "0.6"
      replicaCount: 1
    ingress:
      enabled: true
      host: omnitools.shakir.cloud
      ingressClassName: nginx
