apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omnitools
spec:
  values:
    app:
      image:
        digest: sha256:ceb5acc317daf387634f7f212cefe4722fd1243ad1cba74203f25254195b6c69
      replicaCount: 1
    ingress:
      enabled: true
      host: omnitools.shakir.cloud
      ingressClassName: nginx
