# This file is used to automatically label issues and pull requests based on the files changed.
# It is used by the GitHub Labeler Action: https://github.com/actions/labeler
docs:
  - changed-files:
    - any-glob-to-any-file: "**/README*"

cluster-dev:
  - changed-files:
      - any-glob-to-any-file: "clusters/dev/**/*"

cluster-prod:
  - changed-files:
      - any-glob-to-any-file: "clusters/prod/**/*"

flux-config:
  - changed-files:
      - any-glob-to-any-file: "clusters/**/flux-system/**/*"
