apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  values:
    # check the base values file for a full list of available values
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: home.shakir.cloud
            paths:
              - path: /
                pathType: Prefix
