apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest
spec:
  values:
    app:
      image:
        digest: sha256:47159a9402291275bd9f8a8ed4f5c1ce8502de216465ed29da8a3c995b807df1
      replicaCount: 1
    ingress:
      enabled: true
      host: speedtest.shakir.cloud
      ingressClassName: nginx

    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      storageClassName: nfs-client
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main
