apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest
spec:
  values:
    app:
      image:
        tag: 1.13.3
      replicaCount: 1
    ingress:
      enabled: true
      host: speedtest.shakir.cloud
      ingressClassName: nginx

    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      storageClassName: nfs-client
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main
