apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
spec:
  values:
    app:
      image:
        digest: sha256:95d528cb4f8d18e0fbdc42ae3d09b5c4a899bfbd6bb89eeaf94b904330d79714
      replicaCount: 1
    ingress:
      enabled: true
      host: draw.shakir.cloud
      ingressClassName: nginx
