apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gaseous
spec:
  values:
    app:
      image:
        tag: v1.7.14
      replicaCount: 1
    ingress:
      enabled: true
      host: games.shakir.cloud
      ingressClassName: nginx
    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/gaseous
