apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: default

spec:
  interval: 1h0m0s
  releaseName: karakeep

  chart:
    spec:
      chart: karakeep
      version: "0.27.0"
      sourceRef:
        kind: HelmRepository
        name: karakeep
        namespace: flux-system
      interval: 2h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: karakeep-values
      valuesKey: values.yaml
