apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lubelogger
spec:
  values:
    ingress:
      enabled: true
      className: "traefik"
      annotations: {}
      hosts:
        - host: car.shakir.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
