apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-wordpress
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: wordpress-values
      valuesKey: wp-values.yaml

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress-data
  namespace: default
spec:
  interval: 5m
  releaseName: wordpress-data
  chart:
    spec:
      chart: nfspersistence
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: wordpress-data
      valuesKey: wp-data-values.yaml
