apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
spec:
  values:
    applicationHost: karakeep.shakir.cloud

    ingress:
      karakeep:
        enabled: true
        className: "nginx"
        hosts:
          - host: karakeep.shakir.cloud
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: karakeep
                  identifier: karakeep
                  port: http
