apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system

spec:
  interval: 1h0m0s
  releaseName: loki-stack

  chart:
    spec:
      chart: loki-stack
      version: "2.10.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 2h0m0s

  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
