apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deemix
  namespace: default

spec:
  interval: 5m
  releaseName: deemix

  chart:
    spec:
      chart: unichart
      version: "0.0.5"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  valuesFrom:
    - kind: ConfigMap
      name: deemix-values
      valuesKey: values.yaml
