apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-deployment
  namespace: default
spec:
  interval: 1h0m0s
  releaseName: gha-runner-deployment
  chart:
    spec:
      chart: gha-runner-deployment
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 2h0m0s
  values:
    name: 'dev-runner'
    namespace: 'default'
    repository: 'tinycloud-labs/infrastructure'
