apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
spec:
  values:
    app:
      image:
        tag: "2025.12.14"
      replicaCount: 1
    ingress:
      enabled: true
      host: metube.shakir.cloud
      ingressClassName: nginx
    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/metube
