apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  values:
    app:
      image:
        tag: sha-fb8c8c0
      replicaCount: 1
    ingress:
      enabled: true
      host: bentopdf.shakir.cloud
      ingressClassName: traefik
