apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  values:
    app:
      image:
        digest: sha256:b55f663d570c834f50edfd6ff67b1867f306b48993deeeda7c78378080b48000
      replicaCount: 1
    ingress:
      enabled: true
      host: bentopdf.shakir.cloud
      ingressClassName: nginx

