apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  values:
    app:
      image:
        tag: latest
      replicaCount: 1
    ingress:
      enabled: true
      host: bentopdf.shakir.cloud
      ingressClassName: nginx

