app:
  name: speedtest
  image:
    repository: linuxserver/speedtest-tracker
    pullPolicy: IfNotPresent
    tag: 1.15.0@sha256:1193562c4ab4fe29cffd5e6ad4c042a2ed02e218999bedc7c801c96e032d9f9b
  containerPort: 80

  service:
    port: 80
    targetPort: 80

  volumeMounts:
    - mountPath: /config
      subPath: config

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "America/Los_Angeles"
    - name: OOKLA_EULA_GDPR
      value: "true"
    - name: DB_CONNECTION
      value: sqlite
