apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deemix
spec:
  values:
    app:
      image:
        digest: sha256:a942d7e504e08f84bee249d418e228aee3c62f24bc313e2402ff197b4ce7deaf
      replicaCount: 1

    ingress:
      enabled: true
      host: deemix.shakir.cloud
      ingressClassName: nginx

    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/deemix
