apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lubelogger
  namespace: default

spec:
  interval: 1h0m0s
  releaseName: lubelogger

  chart:
    spec:
      chart: lubelogger
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      interval: 2h0m0s

  valuesFrom:
    - kind: ConfigMap
      name: carlogger-values
      valuesKey: values.yaml
