app:
  name: metube
  image:
    repository: ghcr.io/alexta69/metube
    pullPolicy: IfNotPresent
    tag: "2026.08.18@sha256:20cdbbf51b8051214ab92baa551683357532d2bebf70c3a0e1ec54f072cce999" # renovate: depName=ghcr.io/alexta69/metube
  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 8081

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads

