app:
  name: metube
  image:
    repository: ghcr.io/alexta69/metube
    pullPolicy: IfNotPresent
    tag: "2026.08.04@sha256:9c23af6491bea0761400d7f80f25cfe001847c55b66d20e32ceb17f9527afd29" # renovate: depName=ghcr.io/alexta69/metube
  replicaCount: 1

  containerPort: 80

  service:
    port: 80
    targetPort: 8081

  volumeMounts:
    - mountPath: /downloads
      subPath: downloads

