app:
  name: bentopdf
  image:
    repository: ghcr.io/alam00000/bentopdf
    pullPolicy: IfNotPresent
    tag: 2.8.7@sha256:165113f4579cc61ea353ad0597ed510cc2101ef879ec5e91875a3df0c0b219a0 # renovate: depName=ghcr.io/alam00000/bentopdf
  containerPort: 8080

  service:
    port: 80
    targetPort: 8080
