apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
spec:
  values:
    app:
      image:
        tag: sha-4bfc5bb
      replicaCount: 1
    ingress:
      enabled: true
      host: draw2.shakir.cloud
      ingressClassName: traefik
