apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: default

spec:
  interval: 5m
  releaseName: metube

  chart:
    spec:
      chart: unichart
      version: "0.0.3"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    app:
      name: s-pdf
      image:
        repository: frooodle/s-pdf
        tag: latest
        pullPolicy: IfNotPresent

      replicaCount: 1

      service:
        port: 80
        targetPort: 8080

      volumeMounts:
        - mountPath: /customfiles
          subPath: customfiles
        - mountPath: /configs
          subPath: configs
        - mountPath: /usr/share/tessdata
          subPath: tessdata

      env:
        - name: DOCKER_ENABLE_SECURITY
          value: "true"
        - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
          value: "false"
        - name: LANGS
          value: "en_US"

    ingress:
      enabled: true
      host: spdf.shakir.cloud
      ingressClassName: nginx

    nfspersistence:
      enabled: true
      persistence:
        name: spdf-pvc
        storageClassName: nfs-client
        accessMode: ReadWriteMany
        reclaimPolicy: Retain
        size: 200Mi
      labels:
        app: spdf
      annotations:
        volume.kubernetes.io/description: "Shared volume for spdf"
        custom.synology/path-hint: "Dynamic Provision - Check the PVC-ID"
