apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: default
spec:
  interval: 5m
  releaseName: excalidraw
  chart:
    spec:
      chart: unichart
      version: '0.0.1'
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m
  values:
    app:
      name: "excalidraw"
      image:
        repository: "excalidraw/excalidraw"
        tag: "latest"
        pullPolicy: IfNotPresent

      replicaCount: 1

      service:
        port: 80
        targetPort: 80

    ingress:
      enabled: true
      host: "draw.shakir.cloud"
      ingressClassName: nginx
