apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spdf
  namespace: default

spec:
  interval: 5m
  releaseName: spdf

  chart:
    spec:
      chart: unichart
      version: "0.0.4"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    app:
      name: s-pdf
      image:
        repository: frooodle/s-pdf
        tag: latest
        pullPolicy: IfNotPresent

      replicaCount: 1

      service:
        port: 80
        targetPort: 8080

      volumeMounts:
        - mountPath: /customfiles
          subPath: customfiles
        - mountPath: /configs
          subPath: configs
        - mountPath: /usr/share/tessdata
          subPath: tessdata

      env:
        - name: DOCKER_ENABLE_SECURITY
          value: "true"
        - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
          value: "false"
        - name: LANGS
          value: "en_US"

    ingress:
      enabled: true
      host: spdf.shakir.cloud
      ingressClassName: nginx

    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      storageClassName: nfs-client
      nfs:
        server: nas.shakir.cloud
        path: /volume1/k3s-main
