apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default

spec:
  interval: 5m
  releaseName: paperless-ngx

  dependsOn:
    - name: paperless-ngx-data
      namespace: apps

  chart:
    spec:
      chart: paperless-ngx
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    app:
      paperlessngx:
        image:
          repository: ghcr.io/paperless-ngx/paperless-ngx
          tag: 2.16.3
          pullPolicy: IfNotPresent

        env:
          - name: PAPERLESS_URL
            value: "https://paperless.shakir.cloud"
          - name: PAPERLESS_TIME_ZONE
            value: "America/Los_Angeles"
          - name: PAPERLESS_OCR_LANGUAGE
            value: "eng"
          - name: "PAPERLESS_OCR_LANGUAGES"
            value: "ara"
          - name: PAPERLESS_FILENAME_FORMAT
            value: "{{ correspondent }}/{{ created_year }}-{{ created_month }}-{{ title }}"
          - name: PAPERLESS_CONSUMER_POLLING
            value: "30"

      adminSecret:
        enabled: true
        create: true
        name: paperless-ngx-admin
        usernameKey: username
        passwordKey: password
        username: admin
        password: changeme

      redis:
        image:
          repository: docker.io/library/redis
          tag: "8"
          pullPolicy: IfNotPresent

      persistence:
        shared:
          existingClaim: paperless-ngx-data

      ingress:
        enabled: true
        host: paperless.shakir.cloud
        ingressClassName: nginx
        annotations: {}
