apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: - release-paperless-ngx-data.yaml
  namespace: default

spec:
  interval: 5m
  releaseName: paperless-ngx-data

  chart:
    spec:
      chart: nfspersistence
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    labels:
      app: paperless-ngx
    annotations:
      volume.kubernetes.io/description: "Shared PVC for paperless-ngx"
      custom.synology/path-hint: "maps to /vol1/k3s-main/paperless-ngx"

    persistence:
      name: paperless-ngx-data
      size: 100Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/paperless-ngx
