apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omnitools
  namespace: default

spec:
  interval: 5m
  releaseName: omnitools

  chart:
    spec:
      chart: unichart
      version: "0.0.3"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    app:
      name: omnitools
      image:
        repository: iib0011/omni-tools
        tag: latest
        pullPolicy: IfNotPresent

      replicaCount: 1

      containerPort: 80

      service:
        port: 80
        targetPort: 80

    ingress:
      enabled: true
      host: omnitools.shakir.cloud
      ingressClassName: nginx
