apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: default

spec:
  interval: 5m
  releaseName: actualbudget

  chart:
    spec:
      chart: unichart
      version: "0.0.5"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    app:
      name: actualbudget
      image:
        repository: docker.io/actualbudget/actual-server
        tag: "sha-a9047bf"
        pullPolicy: IfNotPresent

      replicaCount: 1

      service:
        port: 80
        targetPort: 5006

      volumeMounts:
        - mountPath: /data
          subPath: data

      livenessProbe:
        enabled: true
        command: ["node", "src/scripts/health-check.js"]
        initialDelaySeconds: 20
        periodSeconds: 60
        timeoutSeconds: 10
        failureThreshold: 3

    ingress:
      enabled: true
      host: budget.shakir.cloud
      ingressClassName: nginx

    persistence:
      enabled: true
      size: 200Mi
      accessMode: ReadWriteMany
      reclaimPolicy: Retain
      nfs:
        server: synology.shakir.cloud
        path: /volume1/k3s-main/actualbudget
