apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: default

spec:
  interval: 5m
  releaseName: metube

  chart:
    spec:
      chart: unichart
      version: "0.0.3"
      sourceRef:
        kind: HelmRepository
        name: tinycloud-labs
        namespace: flux-system
      interval: 1m

  values:
    app:
      name: metube
      image:
        repository: ghcr.io/alexta69/metube
        tag: latest
        pullPolicy: IfNotPresent

      replicaCount: 1

      containerPort: 80

      service:
        port: 80
        targetPort: 8081

      volumeMounts:
        - mountPath: /downloads
          subPath: downloads

    ingress:
      enabled: true
      host: metube.shakir.cloud
      ingressClassName: nginx

    nfspersistence:
      enabled: true
      persistence:
        name: metube-pvc
        storageClassName: "nfs-client"
        accessMode: ReadWriteMany
        reclaimPolicy: Retain
        size: 200Mi
      labels:
        app: "metube"
      annotations:
        volume.kubernetes.io/description: "Shared volume for metube"
        custom.synology/path-hint: "Dynamic Provision - Check the PVC-ID"
