apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  dependsOn:
    - name: prometheus-stack
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
